### ISSUE TITLE
This works insanely good

### ISSUE THREAD

**Issue by loeffel-io** [luabagg/orc-generator#10]
Really good job! Works so much better then wkhtmltopdf

I would love to migrate to this with https://github.com/loeffel-io/mail-downloader.

1) For integration it would be great to create the file myself, for instance:

```
	orcgen.Generate(
		htmlBody,
		orcgen.PDFConfig{
			Landscape:         false,
			PrintBackground:   true,
			PreferCSSPageSize: true,
		}
	)
```
should return the file bytes and the error to create the file myself with the permissions i want etc

2) With wkhtmltopdf i was able to disable javascript - is this possible?

3) I would love to do the download of the browser before i start converting pdfs, because this results in:

```
322 / 322 [----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------->] 100.00% 47 p/sProcessing messages...
5 / 322 [--->______________________________________________________________________________________________________________________________________________________________________________________________________] 1.55% 78 p/s[launcher.Browser]2024/11/28 19:12:09 Download: https://storage.googleapis.com/chromium-browser-snapshots/Mac_Arm/1294824/chrome-mac.zip
5 / 322 [--->______________________________________________________________________________________________________________________________________________________________________________________________________] 1.55% 78 p/s[launcher.Browser]2024/11/28 19:12:09 Progress: 00%
5 / 322 [--->______________________________________________________________________________________________________________________________________________________________________________________________________] 1.55% 68 p/s[launcher.Browser]2024/11/28 19:12:10 Progress: 07%
```

4) German umlauts prints as `Sie mÃ¶cht`. Would be great to have UTF-8 (?)

Thank you!

**Comment by luabagg** [comment]
Thanks for the feedback!

1. It's already possible:

```
	fileinfo, err = orcgen.NewHandler(orcgen.PDFConfig{
		PrintBackground: true,
		PageRanges:      "1,2",
	}).GenerateFile(page)

	if err == nil {
		filename := "google.pdf"
		fileinfo.Output(getName(filename))
		fmt.Printf("%s generated successfully\n", filename)
	}
```
FileInfo struct: 
```
type Fileinfo struct {
	File     []byte
	Filesize int
}
```


2, 3: I think you can disable Javascript and configure your browser path, but I would have to take a look at go-rod API

For this, I would have to do some changes in the Webdrive file. Maybe I can create an interface and let it be extendable, but I'll have to take a more detailed look.

**Comment by loeffel-io** [comment]
Thanks for your answer!

I saw the new api before you answer, thats much better.

But what is the page? 😅 

```go
func (mail *mail) generatePdf(pdfGen handlers.FileHandler[orcgen.PDFConfig]) (*fileinfo.Fileinfo, error) {
	count := counter.CreateCounter()

	var htmlBody []byte
	for _, body := range mail.Body {
		if mime := mimetype.Detect(body); !mime.Is("text/html") {
			continue
		}

		htmlBody = append(htmlBody, body...)
		count.Next()
	}

	if count.Current() == 0 {
		return nil, nil
	}

	return pdfGen.SetFullPage(true).GenerateFile(&rod.Page{}) ???
}
```

**Comment by luabagg** [comment]
You can take a look at the examples_test.go

```
	page := wd.UrlToPage("https://google.com")
	wd.WaitLoad(page)
	page.MustInsertText("github orcgen package golang").Keyboard.Type(input.Enter)
	wd.WaitLoad(page)
```

This uses the webdriver directly. If you need to change JS and browser settings, I think it's the way to go. I'll problably add these options in the webdriver config later.

But for now, there's a simpler way to get the file bytes:

```
	fileinfo, err = orcgen.ConvertWebpage(
		pdf.New().SetFullPage(true), "https://www.x.com",
	)
```

or 

```
	fileinfo, err := orcgen.ConvertHTML(
		screenshot.New().SetConfig(orcgen.ScreenshotConfig{
			Format: "jpeg",
		}),
		getHTML(),
	)
```

**Comment by loeffel-io** [comment]
no i already have the file bytes - i just want to convert my html bytes to the pdf bytes

**Comment by loeffel-io** [comment]
just want to fill the page param:  return pdfGen.SetFullPage(true).GenerateFile(page somehow from my html bytes)

**Comment by loeffel-io** [comment]
(and want to have multi page pdf like here: https://github.com/luabagg/orcgen/issues/2)

**Comment by loeffel-io** [comment]
Ok sorry, got it: `orcgen.ConvertHTML(pdfGen.SetFullPage(true), htmlBody)`

the api could be a bit easier imo but its just amazing

also german umlauts somehow works - maybe its only for some emails

Thank you!

**Comment by loeffel-io** [comment]
Looks like fileInfo is nil in some edge case

49 / 322 [------------------------------>__________________________________________________________________________________________________________________________________________________________________________] 15.22% 4 p/spanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100bcc700]

goroutine 1 [running]:
main.main()
        /Users/loeffel/go/src/github.com/loeffel-io/mail-downloader/main.go:180 +0xf50

**Comment by loeffel-io** [comment]
while the file bytes is not 0 - sure you capture any err in the GenerateHTML function? maybe this happens when the timeout of the webdriver is reached

sorry for all the spam

**Comment by luabagg** [comment]
It's ok

I need more info about where the memory error happened:

![image](https://github.com/user-attachments/assets/e0278433-bc5d-49de-8895-8a59ae43cbd0)


The handler is pretty simple, but you should check for errors.

**Comment by loeffel-io** [comment]
All good, found the issue - was my fault.
Now it would be really great to predownload the browser and disable js.
Then the migration would be done ❤️

**Comment by loeffel-io** [comment]
Sometimes this panics btw, would be good to handle this error

panic: context deadline exceeded

goroutine 1 [running]:
github.com/go-rod/rod/lib/utils.init.func2({0x1016cc3a0?, 0x101ca3980?})
        /Users/loeffel/go/pkg/mod/github.com/go-rod/rod@v0.116.0/lib/utils/utils.go:69 +0x24
github.com/luabagg/orcgen/v2/pkg/webdriver.(*WebDriver).Connect.New.(*Browser).WithPanic.genE.func1({0x14000321790?, 0x140021e0570?, 0x502f?})
        /Users/loeffel/go/pkg/mod/github.com/go-rod/rod@v0.116.0/must.go:36 +0x70
github.com/go-rod/rod.(*Page).MustWaitLoad(0x14002114370)
        /Users/loeffel/go/pkg/mod/github.com/go-rod/rod@v0.116.0/must.go:451 +0x88
github.com/luabagg/orcgen/v2/pkg/webdriver.(*WebDriver).WaitLoad(0x14001080600, 0x14000af0a00?)
        /Users/loeffel/go/pkg/mod/github.com/luabagg/orcgen/v2@v2.0.2/pkg/webdriver/webdriver.go:86 +0x30
github.com/luabagg/orcgen/v2.ConvertHTML[...]({0x101768e00?, 0x1400020ca90}, {0x14000af0a00, 0x502f, 0x5500})
        /Users/loeffel/go/pkg/mod/github.com/luabagg/orcgen/v2@v2.0.2/orcgen.go:73 +0xbc
main.(*mail).generatePdf(0x14000218b40, {0x101768e00, 0x1400020ca90})
        /Users/loeffel/go/src/github.com/loeffel-io/mail-downloader/mail.go:131 +0x158
main.main()
        /Users/loeffel/go/src/github.com/loeffel-io/mail-downloader/main.go:178 +0x101c

**Comment by luabagg** [comment]
Hey, I will be really busy these following weeks - feel free to contribute if you need something faster

**Comment by loeffel-io** [comment]
Hey @luabagg, any update on this? would be amazing to see some progress here

**Comment by luabagg** [comment]
I forgot about this issue

Can you share some files so I can simulate it?

**Comment by loeffel-io** [comment]
I found the exact email which causes the issue: https://app.sparkmailapp.com/web-share/EvhewZP13SJ_lupf5RwfZBro10BH9LKhONW-_LbB

the issue could be the moving gif?

**Comment by luabagg** [comment]
> I found the exact email which causes the issue: https://app.sparkmailapp.com/web-share/EvhewZP13SJ_lupf5RwfZBro10BH9LKhONW-_LbB
> 
> the issue could be the moving gif?

Yes, email me at luanbaggio0@gmail.com

**Comment by loeffel-io** [comment]
Just forwarded the email to you ❤

**Comment by luabagg** [comment]
Really sorry for the delay, I've been really busy, looking into this rn.

**Comment by loeffel-io** [comment]
hey @luabagg, any updates?

**Comment by luabagg** [comment]
> hey [@luabagg](https://github.com/luabagg), any updates?

Couldn't find the issue and didn't have much time to investigate :( you will have to forgive me

I'm working full time and studying so this is really my least priority :/ - I intend to update it in my college winter break (2-3 weeks from now)

**Comment by loeffel-io** [comment]
sounds great, thank you! 🙏

**Comment by loeffel-io** [comment]
hey @luabagg, sorry for the stress, do you had the chance to look into it? 🙏

**Comment by luabagg** [comment]
@loeffel-io no worries, I really abandoned the project. I'm updating/improving the whole project so it might get fixed. I will let you know when I finish it. Also, I plan on renaming it to something more suggestive
